/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef TEXT_GAME_PRIVATE_H
#define TEXT_GAME_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.0.0.67"
#define VER_MAJOR	0
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	67
#define COMPANY_NAME	""
#define FILE_VERSION	""
#define FILE_DESCRIPTION	""
#define INTERNAL_NAME	"TextGame101"
#define LEGAL_COPYRIGHT	"GNU GPL v3.0 License"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"Text Based Game"
#define PRODUCT_VERSION	""

#endif /*TEXT_GAME_PRIVATE_H*/
